#!/usr/bin/python3
# EASY-INSTALL-SCRIPT: 'pwnedpasswords==2.0.0','pwnedpasswords'
__requires__ = 'pwnedpasswords==2.0.0'
__import__('pkg_resources').run_script('pwnedpasswords==2.0.0', 'pwnedpasswords')
