var script_tag=document.getElementById('builderall_socialproof');var proof_url='https://proof.builderall.com/';var query=script_tag.src.replace(/^[^\?]+\??/,'');var vars=query.split("&");var args={};for(var i=0;i<vars.length;i++){var pair=vars[i].split("=");args[pair[0]]=decodeURI(pair[1]).replace(/\+/g,' ');}
var campaignId=args['id'];var baSPrecords=[];var campaignInfo;var currentRecord=0;var interval;function getName(name){if(name.indexOf('|')>0){var array=name.split('|');return array[Math.floor(Math.random()*array.length)];}
return name;}
function getRecords(campaignId){var xhr=new XMLHttpRequest();xhr.open('POST','https://proof.builderall.com/api/getRecords.php?id='+campaignId,true);xhr.onload=function(){var obj=JSON.parse(this.responseText);baSPrecords=[];for(var i=0;i<obj.data.length;i++){baSPrecords.push(obj.data[i]);}
baSPrecords=baSPrecords.sort((a,b)=>{if(Date.parse(a.date)>Date.parse(b.date)){return-1;}else if(Date.parse(a.date)<Date.parse(b.date)){return 1;}else{return 0;}});campaignInfo=obj.campaign_info;var styleSheet=document.createElement("style");styleSheet.type="text/css";styleSheet.innerHTML=campaignInfo.custom_css;document.head.appendChild(styleSheet);console.log("Social Proof loaded");clearInterval(interval);interval=setInterval(showPopup,(+campaignInfo.show_interval+ +campaignInfo.show_duration)*1000);};xhr.send();}
function showPopup(){var currentRecord=getCurrentRecord();if(currentRecord!=null){if(campaignInfo.display_on_mobile=='1'||(campaignInfo.display_on_mobile=='0'&&!mobileCheck())){var div=document.createElement('div');div.id='builderall_social_proof';div.className='basp_'+campaignInfo.position+' fade-in basp_'+campaignInfo.theme;if(campaignInfo.url_to_navigate!=''){div.className+=' with-pointer';}
div.onclick=function(){var xhr=new XMLHttpRequest();xhr.open('POST','https://proof.builderall.com/api/addClick.php',true);xhr.setRequestHeader('Content-type','application/x-www-form-urlencoded');xhr.send('campaign_id='+campaignId+'&url='+location.href);if(campaignInfo.url_to_navigate!=''){window.open(campaignInfo.url_to_navigate,'_blank');}};console.log('display social proof popup');document.body.append(div);if(campaignInfo.translation_keys.is_rtl=='1'){div.setAttribute('dir','rtl');}else{div.setAttribute('dir','auto');}
var iconData='<div class="basp_empty_image"></div>';if(campaignInfo.icon!=''){iconData='<img alt="" src="'+proof_url+campaignInfo.icon+'" class="basp_icon" />';}
div.innerHTML=iconData+'<span class="basp_user_name">'+getName(currentRecord.user_name)+'</span>';if(campaignInfo.show_from=='1'){div.innerHTML+='<span class="basp_from_lbl"> '+campaignInfo.translation_keys.key_from+' '+currentRecord.location_country+'/'+currentRecord.location_city+'</span>';}
div.innerHTML+='<br /><span class="basp_purchased_lbl">'+campaignInfo.key_purchased+'</span>';var arr=currentRecord.date.split(/[- :]/);var recordDate=new Date(arr[0],arr[1]-1,arr[2],arr[3],arr[4],arr[5]);var currentDate=new Date();var time=((currentDate.getTime()+currentDate.getTimezoneOffset()*60000)-recordDate.getTime())/1000;var whenLabel='';if(time<60){if(campaignInfo.translation_keys.key_seconds.indexOf('{time}')>=0){whenLabel=campaignInfo.translation_keys.key_seconds.replaceAll('{time}',Math.floor(time));}else{whenLabel=Math.floor(time)+' '+campaignInfo.translation_keys.key_seconds;}}else if(time<3600){if(campaignInfo.translation_keys.key_minutes.indexOf('{time}')>=0){whenLabel=campaignInfo.translation_keys.key_minutes.replaceAll('{time}',Math.floor(time/60));}else{whenLabel=Math.floor(time/60)+' '+campaignInfo.translation_keys.key_minutes;}}else if(time<86400){if(campaignInfo.translation_keys.key_hours.indexOf('{time}')>=0){whenLabel=campaignInfo.translation_keys.key_hours.replaceAll('{time}',Math.floor(time/3600));}else{whenLabel=Math.floor(time/3600)+' '+campaignInfo.translation_keys.key_hours;}}else{if(campaignInfo.translation_keys.key_days.indexOf('{time}')>=0){whenLabel=campaignInfo.translation_keys.key_days.replaceAll('{time}',Math.floor(time/86400));}else{whenLabel=Math.floor(time/86400)+' '+campaignInfo.translation_keys.key_days;}}
div.innerHTML+='<br /><span class="basp_when_lbl">'+whenLabel+'</span>';setTimeout(function(){document.body.removeChild(div);},campaignInfo.show_duration*1000);}}}
function getCurrentRecord(){var toReturn;if(currentRecord>baSPrecords.length-1&&baSPrecords.length>0){currentRecord=0;getRecords(campaignId);return null;}
toReturn=baSPrecords[currentRecord];currentRecord++;return toReturn;}
function mobileCheck(){let check=false;(function(a){if(/(android|bb\d+|meego).+mobile|avantgo|bada\/|blackberry|blazer|compal|elaine|fennec|hiptop|iemobile|ip(hone|od)|iris|kindle|lge |maemo|midp|mmp|mobile.+firefox|netfront|opera m(ob|in)i|palm( os)?|phone|p(ixi|re)\/|plucker|pocket|psp|series(4|6)0|symbian|treo|up\.(browser|link)|vodafone|wap|windows ce|xda|xiino/i.test(a)||/1207|6310|6590|3gso|4thp|50[1-6]i|770s|802s|a wa|abac|ac(er|oo|s\-)|ai(ko|rn)|al(av|ca|co)|amoi|an(ex|ny|yw)|aptu|ar(ch|go)|as(te|us)|attw|au(di|\-m|r |s )|avan|be(ck|ll|nq)|bi(lb|rd)|bl(ac|az)|br(e|v)w|bumb|bw\-(n|u)|c55\/|capi|ccwa|cdm\-|cell|chtm|cldc|cmd\-|co(mp|nd)|craw|da(it|ll|ng)|dbte|dc\-s|devi|dica|dmob|do(c|p)o|ds(12|\-d)|el(49|ai)|em(l2|ul)|er(ic|k0)|esl8|ez([4-7]0|os|wa|ze)|fetc|fly(\-|_)|g1 u|g560|gene|gf\-5|g\-mo|go(\.w|od)|gr(ad|un)|haie|hcit|hd\-(m|p|t)|hei\-|hi(pt|ta)|hp( i|ip)|hs\-c|ht(c(\-| |_|a|g|p|s|t)|tp)|hu(aw|tc)|i\-(20|go|ma)|i230|iac( |\-|\/)|ibro|idea|ig01|ikom|im1k|inno|ipaq|iris|ja(t|v)a|jbro|jemu|jigs|kddi|keji|kgt( |\/)|klon|kpt |kwc\-|kyo(c|k)|le(no|xi)|lg( g|\/(k|l|u)|50|54|\-[a-w])|libw|lynx|m1\-w|m3ga|m50\/|ma(te|ui|xo)|mc(01|21|ca)|m\-cr|me(rc|ri)|mi(o8|oa|ts)|mmef|mo(01|02|bi|de|do|t(\-| |o|v)|zz)|mt(50|p1|v )|mwbp|mywa|n10[0-2]|n20[2-3]|n30(0|2)|n50(0|2|5)|n7(0(0|1)|10)|ne((c|m)\-|on|tf|wf|wg|wt)|nok(6|i)|nzph|o2im|op(ti|wv)|oran|owg1|p800|pan(a|d|t)|pdxg|pg(13|\-([1-8]|c))|phil|pire|pl(ay|uc)|pn\-2|po(ck|rt|se)|prox|psio|pt\-g|qa\-a|qc(07|12|21|32|60|\-[2-7]|i\-)|qtek|r380|r600|raks|rim9|ro(ve|zo)|s55\/|sa(ge|ma|mm|ms|ny|va)|sc(01|h\-|oo|p\-)|sdk\/|se(c(\-|0|1)|47|mc|nd|ri)|sgh\-|shar|sie(\-|m)|sk\-0|sl(45|id)|sm(al|ar|b3|it|t5)|so(ft|ny)|sp(01|h\-|v\-|v )|sy(01|mb)|t2(18|50)|t6(00|10|18)|ta(gt|lk)|tcl\-|tdg\-|tel(i|m)|tim\-|t\-mo|to(pl|sh)|ts(70|m\-|m3|m5)|tx\-9|up(\.b|g1|si)|utst|v400|v750|veri|vi(rg|te)|vk(40|5[0-3]|\-v)|vm40|voda|vulc|vx(52|53|60|61|70|80|81|83|85|98)|w3c(\-| )|webc|whit|wi(g |nc|nw)|wmlb|wonu|x700|yas\-|your|zeto|zte\-/i.test(a.substr(0,4)))check=true;})(navigator.userAgent||navigator.vendor||window.opera);return check;};if(!document.getElementById('builderall_social_proof_css')){var head=document.getElementsByTagName('head')[0];var link=document.createElement('link');link.id='builderall_social_proof_css';link.rel='stylesheet';link.type='text/css';link.href=proof_url+'css/style.css?rnd='+Math.random();link.media='all';head.appendChild(link);getRecords(campaignId);}